<?php

const keyboard_model = array(
    START_STATE => MAIN_KEYBOARD,
    SET_BILL_NAME_STATE => CREATE_BILL_INPUT,
    SET_BILL_CONFIRM_NAME_STATE => CONFIRM_BILL_NAME_KEYBOARD,
    SET_BILL_PASSWORD_INPUT_STATE => INPUT_PASSWORD_KEYBOARD,
    SET_BILL_PASSWORD_CONFIRM_STATE => CONFIRM_PASSWORD_KEYBOARD,
);