<?php
const MAIN_KEYBOARD = [
    "one_time" => false,
    "buttons" => [[
        ["action" => [
            "type" => "text",
            "payload" => '{"command": "create_user_bill"}',
            "label" => CREATE_BILL_BUTTON_TEXT],
            "color" => "positive"]],
        [["action" => [
            "type" => "text",
            "payload" => '{"command": "show_user_bills"}',
            "label" => SHOW_BILLS_BUTTON_TEXT],
            "color" => "primary"]],
        [["action" => [
            "type" => "text",
            "payload" => '{"command":"start"}',
            "label" => "test STart"]]],
        [["action" => [
            "type" => "text",
            "payload" => '{"command": "help"}',
            "label" => HELP_TEXT],
            "color" => "secondary"]]]];