<?php
const START_STATE = 0;
const SET_BILL_NAME_STATE = 10;
const SET_BILL_CONFIRM_NAME_STATE = 11;
const SET_BILL_PASSWORD_INPUT_STATE = 12;
const SET_BILL_PASSWORD_CONFIRM_STATE = 13;
const SET_BILL_PERSONS_STATE = 14;
const MAIN_BILL_STATE = 20;
const SELECT_SINGLE_BILL_STATE = 21;
const CREATE_SINGLE_BILL_STATE = 22;
const MAIN_SINGLE_BILL_STATE = 23;
