<?php
const START_STATE = 0;
const SET_BILL_NAME_STATE = 10;
const SET_BILL_PASSWORD_INPUT_STATE = 11;
const SET_BILL_PASSWORD_CONFIRM_STATE = 12;
const SET_BILL_PERSONS_STATE = 13;
const MAIN_BILL_STATE = 20;
